### ISSUE TITLE
Feature ability to monitor pvc kubernetes

### ISSUE THREAD

**Issue by ayamGelo** [abahmed/kwatch#103]
**Is your feature request related to a problem? Please describe.**
PVC is great representation of disk in kubernetes, but one problem, no simple problem when we want to monitor usage of this except tricky bash script and setup complex monitoring stacks like grafana and so on

**Describe the solution you'd like**
I think we just need a simplest feature for kwatch right, like when pvc touch 80% or higher send notification to third party and so on whatever, simple problem doesn't need complex installation/solution

**Comment by abahmed** [comment]
@ayamGelo Released on [v0.8.0](https://github.com/abahmed/kwatch/releases/tag/v0.8.0) 🎉
