### ISSUE TITLE
MultiArch Docker image

### ISSUE THREAD

**Issue by QJoly** [abahmed/kwatch#127]
Hello, the Kubernetes cluster I use is only with ARM machines (Raspberry Pi, Rock64). Why not create a multi-arch Docker image to ensure compatibility of Amd64 and Arm64 at the same time.

Documentation : https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by QJoly** [comment]
i tried to build on a raspberry pi 4 and the docker image doesn't works : is Kwatch compatible arm?

**Comment by abahmed** [comment]
@QJoly Dockerfile is fixed, Also, Multi Arch is supported starting for [v0.8.1](https://github.com/abahmed/kwatch/pkgs/container/kwatch)
