### ISSUE TITLE
Update helm chart to add podLabels parameter

### ISSUE THREAD

**Issue by Anindya-Banerjee** [abahmed/kwatch#239]
**Is your feature request related to a problem? Please describe.**
This is a feature request to have a podLabels parameter in the values file. The helm chart currently only allows users to add podAnnotations through the values file. 

**Describe the solution you'd like**
It would be nice to have a podLabels parameter in the values file to add custom labels to the deployment.

**Comment by nwsparks** [comment]
this was completed https://github.com/abahmed/kwatch/pull/325
