### ISSUE TITLE
Question : Init:Error pod failures not detected?

### ISSUE THREAD

**Issue by the4thamigo-uk** [abahmed/kwatch#259]
**Describe the bug**

kwatch does not seem to be picking up pods that fail during the processing of an `initContainer` step. The error that is displayed by `kubectl get pods` is `Init:Error`. Perhaps this error state isnt being picked up, by default?

**Comment by leodahal4** [comment]
Can I take a look for this issue ?

**Comment by abahmed** [comment]
@leodahal4 sure
