### ISSUE TITLE
Rebuild image, update dependencies

### ISSUE THREAD

**Issue by eremeevfd** [abahmed/kwatch#263]
@abahmed It could be great if you could rebuild the image, updating all dependencies, because our security scanners are worried
<img width="1050" alt="Screenshot 2024-01-15 at 15 13 49" src="https://github.com/abahmed/kwatch/assets/9868072/ddfe59de-48e2-4ca6-8052-9a914730b89c">
I think it would be cool to just up patch version for this case, and maybe you can connect dependabot to this repo?

**Comment by abahmed** [comment]
Hello @eremeevfd ,
Thank you for raising this 🙏 
I will release new version after upgrading dependancies right now.

I think we already integrated with dependabot (https://github.com/abahmed/kwatch/blob/main/.github/dependabot.yml#L1)

**Comment by abahmed** [comment]
Fixed in #264

**Comment by eremeevfd** [comment]
@abahmed amazing work, thank you very much!
