### ISSUE TITLE
Support Google Chat

### ISSUE THREAD

**Issue by flobaader** [abahmed/kwatch#269]
Hi there!

I hope this message finds you well. I'd like to kindly request the addition of Google Chat integration to our project. Many of our users are part of the Google Workspaces community, and this feature would greatly enhance their experience. Google Chat, with its support for Markdown, seems like a simpler option to integrate compared to other platforms, although it doesn't support custom block definitions. This integration would offer a more accessible and user-friendly way for our community to use our application within Google Chat.

Thank you so much for considering this request!

**Comment by abahmed** [comment]
@flobaader Released on [v0.9.0](https://github.com/abahmed/kwatch/releases/tag/v0.9.0) 🎉
