### ISSUE TITLE
https://kwatch.dev/ down ?

### ISSUE THREAD

**Issue by thomasLeclaire** [abahmed/kwatch#279]
Hi! 

sounds the website is down, and therefore also the helm repo. 

is it expected? 

thx

**Comment by abahmed** [comment]
Hi @thomasLeclaire 

It works normally from my side 
https://kwatch.dev
https://kwatch.dev/charts/index.yaml

**Comment by amgadramses** [comment]
Working with me as well.

**Comment by thomasLeclaire** [comment]
thx for confirmation! sounds it's something related to cloudflare in fact. Can't really say if it's a real issue or my connection which has been blacklisted from some network for any reason. (but we have some explicit cloudflare front usually in such cases)

but for example : 
curl --resolve kwatch.dev:443:188.114.96.2 https://kwatch.dev --verbose  ==> not working, timeout. 
curl --resolve kwatch.dev:443:104.21.27.34 https://kwatch.dev ==> it is fine


workaournd on my side with some dns overwrite will do the job for now. 

closing ticket like not sure you can or have to do anything, but posting these details if anyone has also the issue!
