### ISSUE TITLE
Feature: support MS Teams as a provider

### ISSUE THREAD

**Issue by BK-STAR77** [abahmed/kwatch#30]
**Is your feature request related to a problem? Please describe.**
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook

**Describe the solution you'd like**
Need to use it to MS Teams to use it to my company

thank you

**Comment by abahmed** [comment]
Hey @BK-STAR77 👋 

Thanks for raising this, we're going to work on it ASAP

**Comment by Andrew44Ashraf** [comment]
Hey @BK-STAR77 and @abahmed, I am working on this issue.

**Comment by abahmed** [comment]
@BK-STAR77 

[v0.2.0](https://github.com/abahmed/kwatch/tree/v0.2.0#readme) is just released! It has support for Microsoft Teams

It would be great if you add your company [here](https://github.com/abahmed/kwatch/#who-uses-kwatch)

Also, Feel free to chat with us on [Discord](https://discord.gg/kzJszdKmJ7) if you need any support
