### ISSUE TITLE
Logs formatting

### ISSUE THREAD

**Issue by thomasLeclaire** [abahmed/kwatch#301]
Hello! 

Current logging of Kwatch use logrus thirdparty which send log to a default formatting logfmt when exported. 

Could be cool to be able to choose this format. 

in particular when running on GKE, logs are all considered as ERROR : 
![image](https://github.com/abahmed/kwatch/assets/43581346/efa3479a-219e-420e-adfd-4ba1371a1f01)

not sure how exactly implement this but such config should do the job to allow GKE to auto map stuffs : 
```
logrus.SetFormatter(&log.JSONFormatter{
    FieldMap: logrus.FieldMap{
        logrus.FieldKeyTime:  "time",
        logrus.FieldKeyLevel: "severity",
        logrus.FieldKeyMsg:   "message",
    },
})
```

**Comment by abahmed** [comment]
@thomasLeclaire Released on [v0.9.0](https://github.com/abahmed/kwatch/releases/tag/v0.9.0) 🎉
