### ISSUE TITLE
feature(slack): Add option to specify channel name

### ISSUE THREAD

**Issue by dineshdb** [abahmed/kwatch#43]
Slack supports specifying channel in the message body so that the same webhook can send messages in different channels. It would be useful to have this feature.

**Comment by abahmed** [comment]
@dineshdb Can you provide more details (e.g. the API documentation)?

**Comment by dineshdb** [comment]
[This](https://api.slack.com/legacy/custom-integrations/messaging/webhooks) is part of legacy integrations feature but is being used widely because of ease of use.

**Comment by agitelzon** [comment]
Being able to select a channel via the Legacy API is depreciated. 
This is posted at the top of that page:
```You're reading this because you're looking for info on legacy custom integrations - an outdated way for teams to integrate with Slack. These integrations lack newer features and they will be deprecated and possibly removed in the future. We do not recommend their use.```

Slack wants you to create unique webhook URLs for each channel that you want to use.

**Comment by nwsparks** [comment]
this implementation is still very widely used. it would be nice to support it.

**Comment by dineshdb** [comment]
Legacy api would be the Python2 for slack. I too suggest that this simple api be supported.
