### ISSUE TITLE
Filter what will be send 

### ISSUE THREAD

**Issue by k4d1sm0** [abahmed/kwatch#59]
Is your feature request related to a problem? Please describe.
We always receive the notification when the pod is in status "Podinitializing", this happens all day, but is a false positive.

Describe the solution you'd like
I would like to filter the "Reason" field on the message, to send to slack just the "CrashLoopback", and another errors, not all the errors.

**Comment by k4d1sm0** [comment]
I saw on the commits, that you insert the PodInitializing in to the ignoreFailedGracefulShutdown

I activated this option, but I still receiving the PodInitializing messages

**Comment by k4d1sm0** [comment]
Sorry, my bad, I put the ignoreFailedGracefulShutdown: true, down the alert.slack. and it works.

**Comment by abahmed** [comment]
@k4d1sm0 Thanks for raising this!
We're going to release these patches today / tomorrow
