### ISSUE TITLE
Ability to keep log more informative

### ISSUE THREAD

**Issue by ardimaul** [abahmed/kwatch#75]
**Is your feature request related to a problem? Please describe.**
There's already support to capture last log line and customize it, but if log message too long slack will trim it,
My experience I set only for last 10 log but still get trim, and quote disappeared at last make message not block by quote

**Describe the solution you'd like**
Maybe we can make that still send full log but via file instead of quote the message? Or only send real last log, instead of first last log that get trimmed

**Comment by 0123hoang** [comment]
+1 for Telegram, I hope this feature will fixed soon.

**Comment by 0123hoang** [comment]
Logs string have \" char so it trimmed.
You can replace it before send to provider, something like that: 
[https://stackoverflow.com/questions/40760490/how-to-trim-char-from-a-string-in-golang](url)
Have fun.

**Comment by ayamGelo** [comment]
Ok, It's fixed in 0.5.0
