### ISSUE TITLE
MS Teams Bad request issue

### ISSUE THREAD

**Issue by akoken** [abahmed/kwatch#76]
**Describe the bug**
Although I set MS Teams channel webhook address in config.yaml file, I didn't get any notifications.

**Expected behavior**
Should get kwatch notification to my MS Teams channel.

**Actual behavior**
When I checked the pod logs, it gives the following error:

time="2022-02-23T13:23:01Z" level=error msg="failed to send msg with Microsoft Teams: call to teams alert returned status code 400: Bad payload received by generic incoming webhook."

**Version/Commit**
0.4.0

**Comment by ibannieto** [comment]
Thank you so much @akoken , my webhook is now working properly :-)

**Comment by akoken** [comment]
I'm glad that it worked for you @ibannieto :)

**Comment by BK-STAR77** [comment]
> I think corporate proxy causes this issue. I rebuilt the docker image by setting proxy and it worked. Guess what? Now Kubernetes API requests are failing with TLS handshake error. Notification-only proxy configuration would most likely work.

Hi, @akoken 

I'm facing the same issue. kwatch don't work with proxy

TLS handshake error with enterprise proxy or i/o timeout when I removed it
